providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
tls:
  cert: /etc/traefik/certificates/cert.pem
  key: /etc/traefik/certificates/key.pem

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  dashboard: true
  insecure: true
